/** 문항 유형 모듈을 import해 registerQuestion(...) 부작용을 실행시킨다. */
import './Cloze'
import './Choice'
import './Short'
import './Combo'
import './Order'
import './Match'
import './Numeric'
import './Math'
import './Chem'
import './DataTable'
import './Drawing'
import './Photo'

export { getQuestionDefinition, isQuestionAnswered, listQuestionDefinitions, registerQuestion } from './registry'
